/// <reference types="react" />
export declare const HomeIcon: () => JSX.Element;
export declare const FinancingIcon: () => JSX.Element;
export declare const TaskIcon: () => JSX.Element;
export declare const DevIcon: () => JSX.Element;
export declare const ChatIcon: () => JSX.Element;
export declare const UxIcon: () => JSX.Element;
export declare const MusicIcon: () => JSX.Element;
export declare const DnaIcon: () => JSX.Element;
export declare const GamesIcon: () => JSX.Element;
export declare const GalleryIcon: () => JSX.Element;
